* Emacs

** <2024-01-20 Sat>

** <2024-01-19 Fri>

** <2024-01-17 Wed>
Used the fontaine package today to set the fonts. Much better if you ask me. Also switched to the iA Writer fonts for note-taking. Beautiful!

** <2024-01-16 Tue>

Lots of Emacs changes and happy the way Emacs looks right now. Only thing that still needs work is the modeline.

** <2023-11-26 Sun>

Let the journaling begin. At some point, I should write a post on how powerful Emacs is combined with LLMs. Knowing how to do it was the only difficulty in a completely malleable environment. Now, we can use LLMs to help.

** Tasks
*** DONE Change LSP in Markdown and Org-mode from eglot to LSP because eglot does not work with code actions.
*** TODO Clean up the modeline. See the following video: [[https://www.youtube.com/watch?v=Qf_DLPIA9Cs][write custom mode line]]
*** TODO Improve the [[https://www.evalapply.org/posts/emerging-from-dotemacs-bankruptcy-ide-experience/index.html#main][Clojure experience in Emacs]].
*** TODO Clean up my Emacs dotfiles with no littering.
